class FileConf:
    GRAPH_QL_JSON = "json/GraphQL.json"
    GRAPH_QL_MD = "markdown/GraphQL.md"
    V11_QL_JSON = "json/v1.1.json"
    V11_QL_MD = "markdown/v1.1.md"
    FREEZE_OBJECT_JSON = "json/FreezeObject.json"
    FREEZE_OBJECT_MD = "markdown/FreezeObject.md"
    CHANGE_LOG_MD = "markdown/ChangeLog.md"
    INITIAL_STATE_JSON = "json/InitialState.json"
    META_DATA_JSON = "json/MetaData.json"
    SCRIPT_LOAD_JSON = "json/ScriptLoadJson.json"
    API_JSON = "json/API.json"
