class FileConf:
    GRAPH_QL_JSON = "docs/json/GraphQL.json"
    GRAPH_QL_MD = "docs/markdown/GraphQL.md"
    V11_QL_JSON = "docs/json/v1.1.json"
    V11_QL_MD= "docs/markdown/v1.1.md"
    FREEZE_OBJECT_JSON = "docs/json/FreezeObject.json"
    FREEZE_OBJECT_MD = "docs/markdown/FreezeObject.md"
    CHANGE_LOG_MD = "docs/markdown/ChangeLog.md"
    INITIAL_STATE_JSON = "docs/json/InitialState.json"
    META_DATA_JSON = "docs/json/MetaData.json"
    SCRIPT_LOAD_JSON = "docs/json/ScriptLoadJson.json"
    API_JSON = "docs/json/API.json"
